# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boosterCpp <- function(x, y, model_name, n_estimators = 100L, learning_rate = 0.1, tolerance = 1e-4, calibration = FALSE, seed = 123L, show_progress = TRUE, verbose = FALSE) {
    .Call(`_tisthemachinelearner_boosterCpp`, x, y, model_name, n_estimators, learning_rate, tolerance, calibration, seed, show_progress, verbose)
}

predictBoosterCpp <- function(booster, x) {
    .Call(`_tisthemachinelearner_predictBoosterCpp`, booster, x)
}

